Renames main.js to app.js
h5bp/html5-boilerplate pull request #2341
Opened 2020-09-24 23:18 UTC by roblarsen

closes #2340

2020-09-28 02:53 UTC, coliff commented
looks good Rob- I think you need to run `gulp build` so that the empty 'app.js' is in the dist directory. (and main.js deleted).

2020-09-28 18:35 UTC, roblarsen commented
@coliff 👀

2020-09-29 02:43 UTC, coliff commented
when I run `gulp build` it updates Modernizr to 3.11.3. it's updated to that version in `package.json` so it should really be the same in dist/ too.

I think we should set dependabot to ignore Modernizr updates - that should be updated manually as it requires a new build of H5Bp to be made. Otherwise we get issues like this... I'll look into that.

2020-09-29 03:16 UTC, roblarsen commented
Yeah, the latest modernizr is included here. We should look into it so that it's manual and not depdendabot driven, for sure. But this one was never updated.

2020-09-29 07:21 UTC, sthiepaan requested changes
Looks promising! Please have a look at the suggested change(s). Thank you! ✌️

2020-09-29 07:21 UTC, sthiepaan commented on src/doc/usage.md
>  │       └── modernizr.min.js
Normally in operating systems, code editors and/or _IDE_, folders are listed before files. In that case `vendor/` should be placed before `app.js`. Can we move folders before files on tree structure so it is listed properly?

2020-09-29 07:34 UTC, sthiepaan commented
@coliff _dependabot_ have [ignored_updates](https://dependabot.com/docs/config-file/#ignored_updates) option which should solve that problem. The downside of doing this is that we need to be aware of bumping ignored package(s) manually 🤷‍♂️

2020-09-29 11:25 UTC, roblarsen commented
@sthiepaan Since Modernizr is actually shipped with this project, I already watch it actively.

2020-09-29 14:29 UTC, roblarsen commented
I'll merge this tonight (GMT -04:00)

2020-09-30 02:20 UTC, merged